### ISSUE TITLE
[BUG] - ImageUtilities|BetterFriendList (Full Client Crash)

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [mwittrien/BetterDiscordAddons#1389]
**Describe the bug**
discord client crashes when trying to right-click on bots in servers with at least 1000+ users in them, or 1000+ messages in them.

**To Reproduce**
this bug is very unpredictable, I've had the most successes in reproducing it when restarting the whole discord client with **image utilities** enabled, when client restarts it should load into a large server ASAP, sometimes the bug doesn't occur till more than one plugin is enabled with **image utilities**, it seems to trigger when some unknown limit is reached.

Edit: this is also happening with **BetterFriendList**

1. Image utilities OR BetterFriendList enabled
2. close & restart client
3. load into big server & right-click on a bot to trigger a crash
 ឵឵3a. if it fails to crash, enable more plugins, repeat steps 1-3 & try to trigger crash again.

**Expected behavior**
for it not to crash my whole discord client

**Screenshots**
![Screen Shot 2022-02-08 at 8 02 45 pm](https://user-images.githubusercontent.com/2242880/152956789-a15ab334-4bd1-4cc3-8f33-35beb2e095b2.jpg)

**Discord Build (stable, ptb or canary):**
```text
Stable 113854 (5d440f1)
BetterDiscord 1.5.1
Host 0.0.264 OS X 10.15.7 (20.6.0)
```

**Additional context**
[discord.com-1644310976265.log](https://github.com/mwittrien/BetterDiscordAddons/files/8022387/discord.com-1644310976265.log)
[discord.com-1644319067525.log](https://github.com/mwittrien/BetterDiscordAddons/files/8023318/discord.com-1644319067525.log)
[with ImageUtilities debug.log](https://github.com/mwittrien/BetterDiscordAddons/files/8022393/debug.log)
[with BetterFriendList debug.log](https://github.com/mwittrien/BetterDiscordAddons/files/8023328/debug.log)
[ImageUtilities Video Demo](https://www.dropbox.com/s/r46uheson8ism0e)
[BetterFriendList Video Demo](https://www.dropbox.com/s/9779xo33nqe3m41) - At 1:03 it doesn't trigger after re-enable, however after full discord client restart with it on at 1:48 it crashes again.

```text
[2022-02-08 09:15:56.397][CONSOLE:ERROR] [Discord] Fatal Error: originalMethod of default in Menu TypeError: Cannot read property 'navId' of undefined
[2022-02-08 09:15:56.398][CONSOLE:ERROR] [Discord] Fatal Error: originalMethod of type in GuildChannelUserContextMenu TypeError: Cannot read property 'user' of undefined
[2022-02-08 09:15:56.439][CONSOLE:ERROR] Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at vu (https://discord.com/assets/18a35ed3ad3a97d032c0.js:5399:351)
    at Mo (https://discord.com/assets/18a35ed3ad3a97d032c0.js:5367:915)
    at https://discord.com/assets/18a35ed3ad3a97d032c0.js:3553:326
    at Wu (https://discord.com/assets/18a35ed3ad3a97d032c0.js:5411:581)
    at t.unstable_runWithPriority (https://discord.com/assets/18a35ed3ad3a97d032c0.js:5536:828)
    at Ki (https://discord.com/assets/18a35ed3ad3a97d032c0.js:5347:117)
    at Hu (https://discord.com/assets/18a35ed3ad3a97d032c0.js:5411:44)
    at yu (https://discord.com/assets/18a35ed3ad3a97d032c0.js:5402:66)
    at https://discord.com/assets/18a35ed3ad3a97d032c0.js:5347:340
    at t.unstable_runWithPriority (https://discord.com/assets/18a35ed3ad3a97d032c0.js:5536:828)
    at Ki (https://discord.com/assets/18a35ed3ad3a97d032c0.js:5347:117)
    at Xi (https://discord.com/assets/18a35ed3ad3a97d032c0.js:5347:285)
    at qi (https://discord.com/assets/18a35ed3ad3a97d032c0.js:5347:220)
    at vu (https://discord.com/assets/18a35ed3ad3a97d032c0.js:5399:510)
    at Object.enqueueSetState (https://discord.com/assets/18a35ed3ad3a97d032c0.js:5351:240)
    at t.h.setState (https://discord.com/assets/18a35ed3ad3a97d032c0.js:5506:297)
    at https://discord.com/assets/18a35ed3ad3a97d032c0.js:725:103
```

this is a very troublesome bug I've had it where it crashes even with image utilities turned off, but after mass disabling/enabling plugins or restarting the client several times it goes away for some time, but it's most consistent with image utilities turned on.

Edit: seems the other plugin was BetterFriendList that was also the root cause, with these two plugins off I haven't experienced any more crashes.

**Comment by mwittrien** [comment]
#1380
