### ISSUE TITLE
[BUG] - EditUsers v4.5.9 - Crashes Discord Stable 

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [mwittrien/BetterDiscordAddons#1685]
**Describe the bug**
after the recent discord update, having this on causes discord to crash

**To Reproduce**
just load into any big server many users & it crashes .

**Expected behavior**
to not crash?

**Screenshots**
<img width="1679" alt="Screen Shot 2022-08-02 at 08 37 14 am" src="https://user-images.githubusercontent.com/2242880/182257480-a5cb05be-e0e7-4dc0-b807-faca99493a97.png">

**Discord Build (stable, ptb or canary):**
```text
Stable 139420 (65dbf29)
BetterDiscord 1.5.3-Hotfix
Host 0.0.267 OS X 10.15.7 (20.6.0)
```

**Additional context**
Log:
```text
[2022-08-01 22:36:17.146][CONSOLE:LOG] [EditUsers] (v4.5.9) has been started
[2022-08-01 22:36:20.776][CONSOLE:WARN] [BDFDB] (v2.4.8) ["hasFlag","isLocalBot","isClaimed"] [proto] not found in WebModules
[2022-08-01 22:36:20.965][CONSOLE:ERROR] i.getAvatarURL is not a function
TypeError: i.getAvatarURL is not a function
    at https://discord.com/assets/f81ff5d822f99c97822f.js:465:201
    at t.n.render (https://discord.com/assets/223d702382084e67b2b6.js:3436:520)
    at qo (https://discord.com/assets/223d702382084e67b2b6.js:6007:489)
    at Xo (https://discord.com/assets/223d702382084e67b2b6.js:6007:288)
    at $s (https://discord.com/assets/223d702382084e67b2b6.js:6047:166)
    at Gu (https://discord.com/assets/223d702382084e67b2b6.js:6037:748)
    at wu (https://discord.com/assets/223d702382084e67b2b6.js:6037:676)
    at Uu (https://discord.com/assets/223d702382084e67b2b6.js:6037:539)
    at Au (https://discord.com/assets/223d702382084e67b2b6.js:6034:164)
    at https://discord.com/assets/223d702382084e67b2b6.js:5979:340
    at t.unstable_runWithPriority (https://discord.com/assets/223d702382084e67b2b6.js:6168:828)
    at Ki (https://discord.com/assets/223d702382084e67b2b6.js:5979:117)
    at qi (https://discord.com/assets/223d702382084e67b2b6.js:5979:285)
    at Xi (https://discord.com/assets/223d702382084e67b2b6.js:5979:220)
    at Tu (https://discord.com/assets/223d702382084e67b2b6.js:6031:510)
    at Object.enqueueForceUpdate (https://discord.com/assets/223d702382084e67b2b6.js:5983:521)
    at t.h.forceUpdate (https://discord.com/assets/223d702382084e67b2b6.js:6138:384)
    at Object.BDFDB.ReactUtils.forceUpdate (betterdiscord://plugins/0BDFDB.plugin.js:3139:152)
    at Object.Internal.forceInitiateProcess (betterdiscord://plugins/0BDFDB.plugin.js:2181:39)
    at Object.BDFDB.PatchUtils.forceAllUpdates (betterdiscord://plugins/0BDFDB.plugin.js:2555:52)
    at EditUsers.forceUpdateAll (betterdiscord://plugins/EditUsers.plugin.js:370:22)
    at EditUsers.onStart (betterdiscord://plugins/EditUsers.plugin.js:291:10)
    at betterdiscord://plugins/0BDFDB.plugin.js:139:51
    at betterdiscord://plugins/0BDFDB.plugin.js:233:15
    at EditUsers.start (betterdiscord://plugins/0BDFDB.plugin.js:140:48)
    at loadComponents (betterdiscord://plugins/0BDFDB.plugin.js:9037:83)
```

**Comment by mwittrien** [comment]
Reload
