### ISSUE TITLE
[BUG] - PersonalPins v2.1.1 - Crashes Discord Stable

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [mwittrien/BetterDiscordAddons#1689]
**Describe the bug**
Discord crashes when trying to filter by all servers On the Personal Pins Tab

**To Reproduce**
Click on "All Servers" in the Personal Pins Window

**Expected behavior**
to show me all my notes & not crash?

**Screenshots**
<img width="743" alt="Screen Shot 2022-08-02 at 11 55 55 am" src="https://user-images.githubusercontent.com/2242880/182275222-233f3977-0d90-430e-8ab5-47391b3e2896.png">
Clicking on the "All Servers Causes Crash"

<img width="1679" alt="Screen Shot 2022-08-02 at 12 02 12 pm" src="https://user-images.githubusercontent.com/2242880/182275854-0d16509c-eb56-4726-b306-dec6a2ae7c05.png">

**Discord Build (stable, ptb or canary):**
```text
Stable 139420 (65dbf29)
BetterDiscord 1.5.3-Hotfix
Host 0.0.267 OS X 10.15.7 (20.6.0)
```

**Additional context**
Log:
```text
[2022-08-02 01:48:08.673][CONSOLE:ERROR] M.getAvatarURL is not a function
TypeError: M.getAvatarURL is not a function
    at W (https://discord.com/assets/e6295b5113d189188282.js:63:707)
    at https://discord.com/assets/e6295b5113d189188282.js:67:244
    at H (https://discord.com/assets/e6295b5113d189188282.js:67:427)
    at betterdiscord://plugins/0PluginLibrary.plugin.js:1650:73
    at so (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:5996:468)
    at Ko (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6006:218)
    at Yo (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6005:547)
    at Ho (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6005:127)
    at $s (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6051:550)
    at Gu (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6039:748)
    at wu (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6039:676)
    at Uu (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6039:539)
    at Au (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6036:164)
    at https://discord.com/assets/d6eb041b5ed7f9ff648f.js:5981:340
    at t.unstable_runWithPriority (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6170:828)
    at Ki (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:5981:117)
    at qi (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:5981:285)
    at Xi (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:5981:220)
    at Ue (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6058:198)
    at en (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:5958:800)
    at HTMLDivElement.r (https://discord.com/assets/6e374320a6e33352f941.js:126:559)
[2022-08-02 01:48:08.680][CONSOLE:ERROR] M.getAvatarURL is not a function
TypeError: M.getAvatarURL is not a function
    at W (https://discord.com/assets/e6295b5113d189188282.js:63:707)
    at https://discord.com/assets/e6295b5113d189188282.js:67:244
    at H (https://discord.com/assets/e6295b5113d189188282.js:67:427)
    at betterdiscord://plugins/0PluginLibrary.plugin.js:1650:73
    at so (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:5996:468)
    at Ko (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6006:218)
    at Yo (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6005:547)
    at Ho (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6005:127)
    at $s (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6051:550)
    at Gu (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6039:748)
    at wu (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6039:676)
    at Uu (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6039:539)
    at Au (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6036:164)
    at https://discord.com/assets/d6eb041b5ed7f9ff648f.js:5981:340
    at t.unstable_runWithPriority (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6170:828)
    at Ki (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:5981:117)
    at qi (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:5981:285)
    at Xi (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:5981:220)
    at Ue (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:6058:198)
    at en (https://discord.com/assets/d6eb041b5ed7f9ff648f.js:5958:800)
    at HTMLDivElement.r (https://discord.com/assets/6e374320a6e33352f941.js:126:559)
```
[debug.log](https://github.com/mwittrien/BetterDiscordAddons/files/9238463/debug.log)

**Comment by mwittrien** [comment]
Reload
