### ISSUE TITLE
[BUG] - SpotifyControls

### ISSUE THREAD

**Issue by jogerj** [mwittrien/BetterDiscordAddons#1999]
**Describe the bug**
React Component Error

**To Reproduce**
Unknown

**Screenshots**

**Discord Build (stable, ptb or canary):**

Stable 156406 (28abb43) Host 1.0.9007 Windows 10 64-Bit (10.0.19045)

**Additional context**
Seems to be randomly occurring, but key seems to be "Could not create React Element! SecurityError: Blocked a frame with origin "https://discord.com" from accessing a cross-origin frame."

<details>

```javascript

e0cb8770be4ce8aba183.js:1529 DOMException: Blocked a frame with origin "https://discord.com" from accessing a cross-origin frame.
    at eval (betterdiscord://plugins/0BDFDB.plugin.js:1233:461)
    at Array.every (<anonymous>)
    at Object.Internal.checkModuleStrings (betterdiscord://plugins/0BDFDB.plugin.js:1233:125)
    at eval (betterdiscord://plugins/0BDFDB.plugin.js:1347:82)
    at Object.BDFDB.ModuleUtils.find (betterdiscord://plugins/0BDFDB.plugin.js:1294:84)
    at Object.Internal.findModule (betterdiscord://plugins/0BDFDB.plugin.js:1217:33)
    at Object.BDFDB.ModuleUtils.findByString (betterdiscord://plugins/0BDFDB.plugin.js:1347:22)
    at Object.Internal.findModuleViaData (betterdiscord://plugins/0BDFDB.plugin.js:2434:53)
    at Object.get (betterdiscord://plugins/0BDFDB.plugin.js:2479:16)
    at SpotifyControls.render (betterdiscord://plugins/SpotifyControls.plugin.js:133:41)
    at qa (https://discord.com/assets/e0cb8770be4ce8aba183.js:1514:489)
    at za (https://discord.com/assets/e0cb8770be4ce8aba183.js:1514:288)
    at $s (https://discord.com/assets/e0cb8770be4ce8aba183.js:1554:166)
    at ku (https://discord.com/assets/e0cb8770be4ce8aba183.js:1544:748)
    at Uu (https://discord.com/assets/e0cb8770be4ce8aba183.js:1544:676)
    at wu (https://discord.com/assets/e0cb8770be4ce8aba183.js:1544:539)
    at yu (https://discord.com/assets/e0cb8770be4ce8aba183.js:1541:164)
    at https://discord.com/assets/e0cb8770be4ce8aba183.js:1486:340
    at t.unstable_runWithPriority (https://discord.com/assets/e0cb8770be4ce8aba183.js:1664:828)
    at Ko (https://discord.com/assets/e0cb8770be4ce8aba183.js:1486:117)
    at Xo (https://discord.com/assets/e0cb8770be4ce8aba183.js:1486:285)
    at qo (https://discord.com/assets/e0cb8770be4ce8aba183.js:1486:220)
    at Au (https://discord.com/assets/e0cb8770be4ce8aba183.js:1541:485)
    at e.t.emit (https://discord.com/assets/e0cb8770be4ce8aba183.js:5960:662)
    at e.t.flushWaitQueue (https://discord.com/assets/e0cb8770be4ce8aba183.js:5981:843)
    at https://discord.com/assets/e0cb8770be4ce8aba183.js:5981:516
    at new Promise (<anonymous>)
    at e.t.dispatch (https://discord.com/assets/e0cb8770be4ce8aba183.js:5981:404)
    at MessageLoggerV2.onDispatchEvent (betterdiscord://plugins/MessageLoggerV2.plugin.js:3039:16)
    at Object.eval [as callback] (betterdiscord://plugins/MessageLoggerV2.plugin.js:654:37)
    at e.dispatch (<anonymous>:4:32701)
    at Ut (https://discord.com/assets/e0cb8770be4ce8aba183.js:4676:670)
    at n.<anonymous> (https://discord.com/assets/e0cb8770be4ce8aba183.js:4681:896)
    at n.i.emit (https://discord.com/assets/e0cb8770be4ce8aba183.js:509:438)
    at n.r._handleGenericDispatch (https://discord.com/assets/e0cb8770be4ce8aba183.js:4647:74)
    at n.r._handleDispatchWithoutQueueing (https://discord.com/assets/e0cb8770be4ce8aba183.js:4642:259)
    at n.r._handleDispatch (https://discord.com/assets/e0cb8770be4ce8aba183.js:4640:775)
    at https://discord.com/assets/e0cb8770be4ce8aba183.js:4639:205
    at r._onDataReady (https://discord.com/assets/e0cb8770be4ce8aba183.js:4634:260)
    at r.x.push.o.handleFlushEnd (https://discord.com/assets/e0cb8770be4ce8aba183.js:4626:403)
    at d.push (https://discord.com/assets/e0cb8770be4ce8aba183.js:1280:156)
    at r.x.push.o.feed (https://discord.com/assets/e0cb8770be4ce8aba183.js:4625:802)
    at WebSocket.<anonymous> (https://discord.com/assets/e0cb8770be4ce8aba183.js:4634:326)
ps @ e0cb8770be4ce8aba183.js:1529
Is.n.payload @ e0cb8770be4ce8aba183.js:1529
Ei @ e0cb8770be4ce8aba183.js:1489
za @ e0cb8770be4ce8aba183.js:1512
$s @ e0cb8770be4ce8aba183.js:1554
ku @ e0cb8770be4ce8aba183.js:1544
Uu @ e0cb8770be4ce8aba183.js:1544
wu @ e0cb8770be4ce8aba183.js:1544
yu @ e0cb8770be4ce8aba183.js:1541
(anonymous) @ e0cb8770be4ce8aba183.js:1486
t.unstable_runWithPriority @ e0cb8770be4ce8aba183.js:1664
Ko @ e0cb8770be4ce8aba183.js:1486
Xo @ e0cb8770be4ce8aba183.js:1486
qo @ e0cb8770be4ce8aba183.js:1486
Au @ e0cb8770be4ce8aba183.js:1541
t.emit @ e0cb8770be4ce8aba183.js:5960
t.flushWaitQueue @ e0cb8770be4ce8aba183.js:5981
(anonymous) @ e0cb8770be4ce8aba183.js:5981
t.dispatch @ e0cb8770be4ce8aba183.js:5981
onDispatchEvent @ MessageLoggerV2.plugin.js:3039
eval @ MessageLoggerV2.plugin.js:654
(anonymous) @ VM481:4
Ut @ e0cb8770be4ce8aba183.js:4676
(anonymous) @ e0cb8770be4ce8aba183.js:4681
i.emit @ e0cb8770be4ce8aba183.js:509
r._handleGenericDispatch @ e0cb8770be4ce8aba183.js:4647
r._handleDispatchWithoutQueueing @ e0cb8770be4ce8aba183.js:4642
r._handleDispatch @ e0cb8770be4ce8aba183.js:4640
(anonymous) @ e0cb8770be4ce8aba183.js:4639
(anonymous) @ e0cb8770be4ce8aba183.js:4634
x.push.o.handleFlushEnd @ e0cb8770be4ce8aba183.js:4626
d.push @ e0cb8770be4ce8aba183.js:1280
x.push.o.feed @ e0cb8770be4ce8aba183.js:4625
(anonymous) @ e0cb8770be4ce8aba183.js:4634
Show 4 more frames
0BDFDB.plugin.js:207 [BDFDB] (v2.9.5) Fatal Error: Could not create React Element! SecurityError: Blocked a frame with origin "https://discord.com" from accessing a cross-origin frame.
Internal.console @ 0BDFDB.plugin.js:207
BDFDB.LogUtils.error @ 0BDFDB.plugin.js:216
componentDidCatch @ 0BDFDB.plugin.js:4704
Is.i.componentDidCatch.n.callback @ e0cb8770be4ce8aba183.js:1530
pi @ e0cb8770be4ce8aba183.js:1489
Ss @ e0cb8770be4ce8aba183.js:1531
Vu @ e0cb8770be4ce8aba183.js:1549
t.unstable_runWithPriority @ e0cb8770be4ce8aba183.js:1664
Ko @ e0cb8770be4ce8aba183.js:1486
Bu @ e0cb8770be4ce8aba183.js:1545
yu @ e0cb8770be4ce8aba183.js:1541
(anonymous) @ e0cb8770be4ce8aba183.js:1486
t.unstable_runWithPriority @ e0cb8770be4ce8aba183.js:1664
Ko @ e0cb8770be4ce8aba183.js:1486
Xo @ e0cb8770be4ce8aba183.js:1486
qo @ e0cb8770be4ce8aba183.js:1486
Au @ e0cb8770be4ce8aba183.js:1541
t.emit @ e0cb8770be4ce8aba183.js:5960
t.flushWaitQueue @ e0cb8770be4ce8aba183.js:5981
(anonymous) @ e0cb8770be4ce8aba183.js:5981
t.dispatch @ e0cb8770be4ce8aba183.js:5981
onDispatchEvent @ MessageLoggerV2.plugin.js:3039
eval @ MessageLoggerV2.plugin.js:654
(anonymous) @ VM481:4
Ut @ e0cb8770be4ce8aba183.js:4676
(anonymous) @ e0cb8770be4ce8aba183.js:4681
i.emit @ e0cb8770be4ce8aba183.js:509
r._handleGenericDispatch @ e0cb8770be4ce8aba183.js:4647
r._handleDispatchWithoutQueueing @ e0cb8770be4ce8aba183.js:4642
r._handleDispatch @ e0cb8770be4ce8aba183.js:4640
(anonymous) @ e0cb8770be4ce8aba183.js:4639
(anonymous) @ e0cb8770be4ce8aba183.js:4634
x.push.o.handleFlushEnd @ e0cb8770be4ce8aba183.js:4626
d.push @ e0cb8770be4ce8aba183.js:1280
x.push.o.feed @ e0cb8770be4ce8aba183.js:4625
(anonymous) @ e0cb8770be4ce8aba183.js:4634
Show 6 more frames
```

</details>

**Comment by mwittrien** [comment]
Sounds like an internet issue

Nothing i can do on my part
