### ISSUE TITLE
[BUG] - PersonalPins, PluginRepo: "React Component Error" + ThemeRepo Crash

### ISSUE THREAD

**Issue by aaronliu0130** [mwittrien/BetterDiscordAddons#2219]
**Describe the bug**
After the latest BDFDB update, the PersonalPins submenu appears but says "React Component Error". The PluginRepo menu says the same thing. ThemeRepo just crashes.

**To Reproduce**
1. Make sure these plugins are installed
2. Click on the PersonalPins topicon, the PluginRepo menu in settings, or the ThemeRepo menu in settings.

**Expected behavior**
no crash and working plugins

**Screenshots**
![image](https://user-images.githubusercontent.com/11874211/222252497-f3cdeec1-b3ff-4e9b-9216-4a2d47f44359.png)
![image](https://user-images.githubusercontent.com/11874211/222252597-cbd60f74-c813-422d-b41f-b7c7a7392dd3.png)

**Discord Build (stable, ptb or canary):**
Stable 177662 (311622e) Host 1.0.9011 (29584

**Additional context**
```
[2023-03-01 20:03:35.732][CONSOLE:ERROR] Cannot read property 'TOP' of undefined
TypeError: Cannot read property 'TOP' of undefined
    at ThemeList.render (betterdiscord://plugins/ThemeRepo.plugin.js:252:56)
    at Cs (https://discord.com/assets/3ce5a3a3ee1992708511.js:1669:100)
    at Rs (https://discord.com/assets/3ce5a3a3ee1992708511.js:1668:890)
    at yu (https://discord.com/assets/3ce5a3a3ee1992708511.js:1709:100)
    at Oc (https://discord.com/assets/3ce5a3a3ee1992708511.js:1701:89)
    at Ic (https://discord.com/assets/3ce5a3a3ee1992708511.js:1701:17)
    at hc (https://discord.com/assets/3ce5a3a3ee1992708511.js:1700:867)
    at ic (https://discord.com/assets/3ce5a3a3ee1992708511.js:1697:642)
    at uc (https://discord.com/assets/3ce5a3a3ee1992708511.js:1698:49)
    at Fo (https://discord.com/assets/3ce5a3a3ee1992708511.js:1637:577)
    at https://discord.com/assets/3ce5a3a3ee1992708511.js:1695:555
[2023-03-01 20:03:38.636][CONSOLE:DEBUG] [ChannelMessagePreviewStore] Persisting store
[2023-03-01 20:03:43.857][CONSOLE:WARN] Window state not initialized window-1
```
Dark mode does NOT help.
This could be unrelated but I also sometimes get [this.](https://user-images.githubusercontent.com/11874211/222253051-da9ed56d-3b61-46ea-9f69-37898571aaf8.png)
<s>muy first pin!!!11!1</s>

**Comment by XxUnkn0wnxX** [comment]
This could be just all BDFD related, as I'm getting errors across many plugins, a heavy amount of errors from the lib
[debug.log](https://github.com/mwittrien/BetterDiscordAddons/files/10870400/debug.log)

<img width="1741" alt="Screen Shot 2023-03-02 at 9 09 33 pm" src="https://user-images.githubusercontent.com/2242880/222405306-f7c61f6e-50c0-4ecd-9a6f-6811ab566119.png">
<img width="1741" alt="Screen Shot 2023-03-02 at 9 09 36 pm" src="https://user-images.githubusercontent.com/2242880/222405338-d6c07f9e-bf11-42bc-b629-0d71535cf60a.png">
<img width="1065" alt="Screen Shot 2023-03-02 at 9 09 39 pm" src="https://user-images.githubusercontent.com/2242880/222405364-e4f609e4-e272-4a86-80a9-d747bdbbed7f.png">
<img width="638" alt="Screen Shot 2023-03-02 at 9 10 41 pm" src="https://user-images.githubusercontent.com/2242880/222405367-d0ac8ce1-6b1e-4e0f-a27e-f9ca06e18b8f.png">
<img width="1142" alt="Screen Shot 2023-03-02 at 9 11 55 pm" src="https://user-images.githubusercontent.com/2242880/222405371-257f9e80-9a63-4cde-b37e-e8cddf93aa70.png">
<img width="1712" alt="Screen Shot 2023-03-02 at 9 36 07 pm" src="https://user-images.githubusercontent.com/2242880/222405375-22a492e0-17f0-4453-9f7c-fb64370683b4.png">
