### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by trfhgx** [mwittrien/BetterDiscordAddons#2357]
**Describe the bug**
when I try to access the plugin settings I get this error 
```
TypeError: BDFDB.ObjectUtils.copy is not a function
    at EditUsers.getUserData (VM549 EditUsers.plugin.js:1294:44)
    at eval (VM549 EditUsers.plugin.js:351:21)
    at Array.map (<anonymous>)
    at Object.children (VM549 EditUsers.plugin.js:350:170)
    at eval (0BDFDB.plugin.js:6872:27)
    at BDFDB_SettingsPanel.render (0BDFDB.plugin.js:6873:10)
    at Ds (47353b94a41d367574d7.js:1794:100)
    at Rs (47353b94a41d367574d7.js:1793:890)
    at gu (47353b94a41d367574d7.js:1834:100)
    at Ic (47353b94a41d367574d7.js:1826:89)
    at mc (47353b94a41d367574d7.js:1826:17)
    at hc (47353b94a41d367574d7.js:1825:867)
    at oc (47353b94a41d367574d7.js:1822:642)
    at uc (47353b94a41d367574d7.js:1823:49)
    at Fi (47353b94a41d367574d7.js:1762:577)
    at 47353b94a41d367574d7.js:1820:555
```
plus whenever I try to change someone's local settings their profile disappears and gets hidden and the option of editing their local setting gets hidden I tried many times to delete the config file and i had no other plugin running but it had no results
**To Reproduce**
whenever I try to access the settings or when I try to change someone's local settings

**Screenshots**
![Screen Shot 2023-05-11 at 5 47 57 PM](https://github.com/mwittrien/BetterDiscordAddons/assets/42844286/4b7f5028-f1e2-46be-8b1a-c8d8e9a5cec1)

**Discord Build (stable, ptb or canary):**
discord ptb(mac)

**Comment by mwittrien** [comment]
Update BDFDB
