### ISSUE TITLE
[BUG] - PLUGIN/ChatFilter

### ISSUE THREAD

**Issue by venturiq** [mwittrien/BetterDiscordAddons#2404]
Gives me this when I try to install the addon.

TypeError: Cannot read properties of undefined (reading 'name')
    at ChatFilter.getName (betterdiscord://plugins/0BDFDB.plugin.js:107:35)
    at M.initializeAddon (betterdiscord/renderer.js:4:34476)
    at M.loadAddon (betterdiscord/renderer.js:4:8506)
    at M.loadAddon (betterdiscord/renderer.js:4:33490)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:4:6315)

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and 0BDFDB.plugin.js and reinstall the BDFDB plugin
