### ISSUE TITLE
[BUG] - BDFDB/ImageUtilities right click options missing

### ISSUE THREAD

**Issue by Leah96xxx** [mwittrien/BetterDiscordAddons#2470]
**Describe the bug**
Right click menu on opened images doesn't work. Instead of displaying the menu items, it shows a little dancing kaomoji. Every other right click menu works fine, but is missing the ImageUtilities options. I have also noticed that only some images will show the file details underneath them.

I have tried both restarting Discord and ctrl+R but the issue persists.

No errors appear in the console when it happens, but during plugin loading the following error appears:

```
c0009414698d6597a8c5.js:536 Error: Menu API only allows Items and groups of Items as children. Received function i(){return null} (object) instead
    at caba9ede029587037deb.js:2990:245
    at Array.reduce (<anonymous>)
    at Do (caba9ede029587037deb.js:2989:14)
    at xo (caba9ede029587037deb.js:2993:142)
    at eval (0BDFDB.plugin.js:2901:21)
    at Sa (caba9ede029587037deb.js:1802:54)
    at gu (caba9ede029587037deb.js:1856:146)
    at Ic (caba9ede029587037deb.js:1849:89)
    at mc (caba9ede029587037deb.js:1849:17)
    at hc (caba9ede029587037deb.js:1848:867)
    at uc (caba9ede029587037deb.js:1845:983)
    at Fi (caba9ede029587037deb.js:1785:577)
    at lc (caba9ede029587037deb.js:1846:498)
    at caba9ede029587037deb.js:1865:522
    at el (caba9ede029587037deb.js:1865:561)
    at t.render (caba9ede029587037deb.js:1869:205)
    at MyReact.render (0BDFDB.plugin.js:2885:40)
    at MyReact.hookCall (0BDFDB.plugin.js:2900:23)
    at loadLibrary (0BDFDB.plugin.js:8018:60)
    at parseData (0BDFDB.plugin.js:1175:24)
    at parseCSS (0BDFDB.plugin.js:1137:122)
    at eval (0BDFDB.plugin.js:1189:7)
    at args.<computed> (0BDFDB.plugin.js:202:20)
    at Function.<anonymous> (renderer.js:4:329975)
```

**To Reproduce**
Right click any image in any channel. For the dancing kaomoji, click and image, then right click the opened image. For the missing file details, just go to any channel with images and see that some are missing.

**Expected behavior**
Right click options from ImageUtilities and file details under most images.

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/88419550/80d9c47c-f2af-40ab-a794-009f261467b4)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/88419550/b994e9f7-43f1-49ec-834a-5524a1409a6c)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/88419550/27bc3242-5d12-4658-ad40-219be722f69f)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
So far I've only noticed the ImageUtilities stuff is missing, but there may be more that I haven't found yet.

**Comment by Leah96xxx** [comment]
I just realised, this may be related to #2469

**Comment by Leah96xxx** [comment]
Confirmed c64eb5d fixes this. Thanks
