### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by iRobsie** [mwittrien/BetterDiscordAddons#2480]
**Describe the bug**
Was typing in a group chat in discord, and the entirety of my discord just crashed, crash recovery plugin was able to save it and print out a debug.

**To Reproduce**
I do not know.

**Expected behavior**
No crashes 😆 but shit happens

**Screenshots**

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Crashlog:
`ed9201fd200830b73101.js:537 [CrashRecovery] HEY OVER HERE! Show this to the plugin developer or in the support server!
Prettified stacktraces, stack:
 Error: Blocked a frame with origin "https://discord.com" from accessing a cross-origin frame.
    at eval (betterdiscord://plugins/0BDFDB.plugin.js:1234:27)
    at Array.every (<anonymous>)
    at Internal.checkModuleProps (betterdiscord://plugins/0BDFDB.plugin.js:1233:69)
    at eval (betterdiscord://plugins/0BDFDB.plugin.js:1342:84)
    at BDFDB.ModuleUtils.find (betterdiscord://plugins/0BDFDB.plugin.js:1291:84)
    at Internal.findModule (betterdiscord://plugins/0BDFDB.plugin.js:1214:33)
    at BDFDB.ModuleUtils.findByProperties (betterdiscord://plugins/0BDFDB.plugin.js:1342:22)
    at Internal.findModuleViaData (betterdiscord://plugins/0BDFDB.plugin.js:2428:75)
    at Object.get (betterdiscord://plugins/0BDFDB.plugin.js:2479:16)
    at ref (betterdiscord://plugins/0BDFDB.plugin.js:7809:56) 
Component stack:
     at div
    at BDFDB_TextScroller (betterdiscord://plugins/0BDFDB.plugin.js:7788:57)
    at div
    at BDFDB_MenuHint (betterdiscord://plugins/0BDFDB.plugin.js:6451:63)
    at div
    at div
    at M (https://discord.com/assets/9a8640bd729d4e4a83be.js:11187:462)
    at n (https://discord.com/assets/9a8640bd729d4e4a83be.js:2731:243)
    at zi (https://discord.com/assets/9a8640bd729d4e4a83be.js:2995:466)
    at L (https://discord.com/assets/9a8640bd729d4e4a83be.js:11186:853)
    at div
    at https://discord.com/assets/9a8640bd729d4e4a83be.js:2809:9
    at div
    at div
    at L (https://discord.com/assets/9a8640bd729d4e4a83be.js:11186:853)
    at div
    at y (https://discord.com/assets/9a8640bd729d4e4a83be.js:2898:263)
    at n (https://discord.com/assets/9a8640bd729d4e4a83be.js:2757:243)
    at div
    at oo (https://discord.com/assets/9a8640bd729d4e4a83be.js:3000:215)
    at div
    at Fi (https://discord.com/assets/9a8640bd729d4e4a83be.js:2994:247)
    at L (https://discord.com/assets/9a8640bd729d4e4a83be.js:11186:853)
    at div
    at https://discord.com/assets/9a8640bd729d4e4a83be.js:2809:9
    at div
    at betterdiscord/renderer.js:4:30222
    at i (betterdiscord/renderer.js:4:375577)
    at L (https://discord.com/assets/9a8640bd729d4e4a83be.js:11186:853)
    at div
    at y (https://discord.com/assets/9a8640bd729d4e4a83be.js:2898:263)
    at n (https://discord.com/assets/9a8640bd729d4e4a83be.js:2757:243)
    at R (https://discord.com/assets/9a8640bd729d4e4a83be.js:2752:889)
    at AppLayer
    at b (https://discord.com/assets/9a8640bd729d4e4a83be.js:2662:529)
    at n (https://discord.com/assets/9a8640bd729d4e4a83be.js:2664:243)
    at R (https://discord.com/assets/9a8640bd729d4e4a83be.js:2665:849)
    at n (https://discord.com/assets/9a8640bd729d4e4a83be.js:2752:93)
    at VerificationLayerProvider
    at p (https://discord.com/assets/9a8640bd729d4e4a83be.js:5665:410)
    at Oe (https://discord.com/assets/9a8640bd729d4e4a83be.js:2544:391)
    at div
    at div
    at n (https://discord.com/assets/9a8640bd729d4e4a83be.js:2752:93)
    at AppLayerProvider
    at E (https://discord.com/assets/9a8640bd729d4e4a83be.js:4984:319)
    at L (https://discord.com/assets/9a8640bd729d4e4a83be.js:11186:853)
    at n (https://discord.com/assets/9a8640bd729d4e4a83be.js:2578:379)
    at T (https://discord.com/assets/9a8640bd729d4e4a83be.js:2581:961)
    at n (https://discord.com/assets/9a8640bd729d4e4a83be.js:2582:655)
    at a (https://discord.com/assets/9a8640bd729d4e4a83be.js:10180:533)
    at p (https://discord.com/assets/9a8640bd729d4e4a83be.js:2532:902)
    at p (https://discord.com/assets/9a8640bd729d4e4a83be.js:2897:209)
    at l (https://discord.com/assets/9a8640bd729d4e4a83be.js:7669:671)
    at en (https://discord.com/assets/9a8640bd729d4e4a83be.js:2563:601)
    at n (https://discord.com/assets/9a8640bd729d4e4a83be.js:3188:245)
    at https://discord.com/assets/9a8640bd729d4e4a83be.js:3192:827
    at a (https://discord.com/assets/9a8640bd729d4e4a83be.js:10179:563)
    at https://discord.com/assets/9a8640bd729d4e4a83be.js:1727:942
    at Dt (https://discord.com/assets/9a8640bd729d4e4a83be.js:1736:248)
    at un (https://discord.com/assets/9a8640bd729d4e4a83be.js:2957:504)
    at App
    at t (https://discord.com/assets/9a8640bd729d4e4a83be.js:1922:520)
    at t (https://discord.com/assets/9a8640bd729d4e4a83be.js:1879:436)
    at ir (https://discord.com/assets/9a8640bd729d4e4a83be.js:3221:100)
    at p (https://discord.com/assets/9a8640bd729d4e4a83be.js:2897:209)
    at l (https://discord.com/assets/9a8640bd729d4e4a83be.js:7669:671)`
    
    if this is unrelated to BDFDB let me know, and I'll properly post it in whatever may have caused the issue.

**Comment by mwittrien** [comment]
Reinstall BD and redownload BDFDB plugin
