### ISSUE TITLE
[BUG] - SpellCheck Plugin is broken

### ISSUE THREAD

**Issue by NoXPhasma** [mwittrien/BetterDiscordAddons#2504]
**Describe the bug**
The SpellCheck Plugin is currently broken. It was unable to load any dictionaries. So I uninstalled it completely, and now it loads itself, but I can't open the settings at all. It says `Could not open settings for SpellCheck`.

This is the error message I see on the console:
```
128b9b02a9aca92d9f18.js:539 [Addon Settings] Unable to get settings panel for SpellCheck. TypeError: Cannot read properties of undefined (reading 'choices')
    at SpellCheck.getSettingsPanel (SpellCheck.plugin.js:126:77)
    at renderer.js:4:86639
    at Object.Me (39d0a34eaa1b4f7f57ea.js:3392:509)
    at Ve (39d0a34eaa1b4f7f57ea.js:3392:663)
    at 39d0a34eaa1b4f7f57ea.js:3413:416
    at Ur (39d0a34eaa1b4f7f57ea.js:3413:513)
    at Gr (39d0a34eaa1b4f7f57ea.js:3413:927)
    at 39d0a34eaa1b4f7f57ea.js:3419:415
    at cc (39d0a34eaa1b4f7f57ea.js:3484:267)
    at Le (39d0a34eaa1b4f7f57ea.js:3391:624)
    at Yr (39d0a34eaa1b4f7f57ea.js:3415:232)
    at Kt (39d0a34eaa1b4f7f57ea.js:3398:858)
    at Zt (39d0a34eaa1b4f7f57ea.js:3398:642)
    at HTMLDivElement.n (128b9b02a9aca92d9f18.js:562:713)
```

**To Reproduce**
1) Install SpellCheck Plugin
2) Try to open the SpellCheck settings

**Expected behavior**
The Plugin should open the settings

**Discord Build (stable, ptb or canary):**
Discord Stable

**Comment by NoXPhasma** [comment]
And now after I opened this issue, it suddenly opens the settings, without me having changed anything.

But now I'm at the same issue I've had before I uninstalled it, it just can't load the dictionaries:
![grafik](https://github.com/mwittrien/BetterDiscordAddons/assets/7719590/06dfb3e7-e911-4aba-9af2-5b4b3ed13f4d)

**Comment by NoXPhasma** [comment]
There was an update of BetterDiscord to version 1.9.4 which fixed this issue.
