### ISSUE TITLE
[BUG] - Translator v2.6.2

### ISSUE THREAD

**Issue by brunoais** [mwittrien/BetterDiscordAddons#2713]
**Describe the bug**
Cannot open plugin settings successfully.

**To Reproduce**
1. Install BDFDB v3.6.7.
3. Install Translator v2.6.2.
4. Enable BDFDB.
5. Enable Translator.
6. Press the gear to change Translator settings.
7. Error message appears about an unexpected error.

**Expected behavior**
The popup appears to input and/or select the options I want for the plugin

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/639467/5900bb24-29f1-49ff-90d1-9580777141ea)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/639467/03d2648e-eba2-4cdf-9d46-95c1ddc87ed5)

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
Console error:
```
TypeError: Cannot read properties of undefined (reading '_currentValue')
    at Object.iI (67096.60fb03d0b62c1fe1124f.js:12:963207)
    at t.useContext (67096.60fb03d0b62c1fe1124f.js:12:1093928)
    at SwitchInner (0BDFDB.plugin.js:7433:43)
    at aS (67096.60fb03d0b62c1fe1124f.js:12:976238)
    at u (67096.60fb03d0b62c1fe1124f.js:12:1031454)
    at sF (67096.60fb03d0b62c1fe1124f.js:12:1014469)
    at 67096.60fb03d0b62c1fe1124f.js:12:1014335
    at sB (67096.60fb03d0b62c1fe1124f.js:12:1014343)
    at sT (67096.60fb03d0b62c1fe1124f.js:12:1011094)
    at sO (67096.60fb03d0b62c1fe1124f.js:12:1011483)
    at r6 (67096.60fb03d0b62c1fe1124f.js:12:960102)
    at 67096.60fb03d0b62c1fe1124f.js:12:1008966
```

**Comment by brunoais** [comment]
Fix confirmed
