### ISSUE TITLE
[BUG] - BDFDB / FriendNotifications - "React Component Error"

### ISSUE THREAD

**Issue by abanichev** [mwittrien/BetterDiscordAddons#2726]
**Describe the bug**
Clicking on button below discord logo leads to "React Component Error"

**To Reproduce**
Click on "Online - N" button below discord logo in the upper-left corner of the window

**Expected behavior**
Plugin interface pops up

**Screenshots**
Just red text "React Component Error". But here is debug log of that error:

```
[2024-06-21 14:42:57.132][CONSOLE:ERROR] Cannot read properties of undefined (reading 'SIZE_40')
TypeError: Cannot read properties of undefined (reading 'SIZE_40')
    at Object.renderItem (betterdiscord://plugins/FriendNotifications.plugin.js:181:68)
    at eval (betterdiscord://plugins/0BDFDB.plugin.js:6740:152)
    at Array.map (<anonymous>)
    at BDFDB_PaginatedList.render (betterdiscord://plugins/0BDFDB.plugin.js:6740:116)
    at o_ (https://discord.com/assets/67096.30c593c3471420b5c889.js:12:975217)
    at og (https://discord.com/assets/67096.30c593c3471420b5c889.js:12:975015)
    at u (https://discord.com/assets/67096.30c593c3471420b5c889.js:12:1016487)
    at sF (https://discord.com/assets/67096.30c593c3471420b5c889.js:12:998521)
    at https://discord.com/assets/67096.30c593c3471420b5c889.js:12:998387
    at sB (https://discord.com/assets/67096.30c593c3471420b5c889.js:12:998395)
    at sT (https://discord.com/assets/67096.30c593c3471420b5c889.js:12:995146)
    at sO (https://discord.com/assets/67096.30c593c3471420b5c889.js:12:995535)
    at r6 (https://discord.com/assets/67096.30c593c3471420b5c889.js:12:944154)
    at https://discord.com/assets/67096.30c593c3471420b5c889.js:12:993018
[2024-06-21 14:42:57.132][CONSOLE:ERROR] [BDFDB] (v3.6.9) Fatal Error: Could not create React Element! TypeError: Cannot read properties of undefined (reading 'SIZE_40')
```

**Discord Build (stable, ptb or canary):**
stable 303557 (3b02892) Host 1.0.9151 x64 (48891) Build Override: N/A Windows 11 64-bit (10.0.22631)

**Additional context**
BDFDB v3.6.9
FriendNotifications v2.0.0

**Comment by B102** [comment]
The red text "React Component Error" goes away when I updated BDFDB to v3.7.0. But still have this red "React Component Error" when I tried to edit my friend list.

**Comment by abanichev** [comment]
Works like a charm again! Thanks @mwittrien <3
