### ISSUE TITLE
[BUG] - 0BDFDB Library sometimes causes Discord to crash.

### ISSUE THREAD

**Issue by Patcheresu** [mwittrien/BetterDiscordAddons#2809]
**Describe the bug**
DevilBro BDFDB version 3.8.5 causes Discord to crash irregularly.

**To Reproduce**
Sporadically when viewing channels or posts.

**Expected behavior**
No crashes whatsoever during normal channel or post viewing.

**Discord Build (stable, ptb or canary):**
stable 342408 (bd62b7c) Host 1.0.9169 x64 (54876) Build Override: N/A Windows 10 64-bit (10.0.19045)
Better Discord Core v1.10.2

**Additional context**

[2024-11-07 15:15:01.234][CONSOLE:ERROR] Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at oJ (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:1058349)
    at f (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:986833)
    at https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:989193
    at o (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:989484)
    at sl (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:1008564)
    at l (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:1055406)
    at oU (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:1036572)
    at https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:1036438
    at ok (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:1036446)
    at oA (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:1033197)
    at oR (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:1033586)
    at r6 (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:982257)
    at https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:1049120
    at oB (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:1049125)
    at oy (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:1032474)
    at b (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:1230240)
    at D (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:1230770)
    at https://discord.com/assets/web.3d2e76993c4bf346a249.js:1:752248
    at O (https://discord.com/assets/web.3d2e76993c4bf346a249.js:1:752013)
    at MessagePort.L (https://discord.com/assets/web.3d2e76993c4bf346a249.js:1:752072)
[2024-11-07 15:15:04.022][CONSOLE:WARN] Window state not initialized window-1

================= Starting Debug Log (2024-11-07 15:15:10.678) =================
[2024-11-07 15:15:11.942][CONSOLE:ERROR] Menu API only allows Items and groups of Items as children. Received function g(e){return null} (object) instead
Error: Menu API only allows Items and groups of Items as children. Received function g(e){return null} (object) instead
    at https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:2550825
    at Array.reduce (<anonymous>)
    at e (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:2549613)
    at v (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:2551034)
    at eval (betterdiscord://plugins/0BDFDB.plugin.js:3012:21)
    at ah (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:995893)
    at l (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:1053577)
    at oU (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:1036572)
    at https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:1036438
    at ok (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:1036446)
    at oR (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:1033531)
    at r6 (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:982257)
    at oD (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:1034035)
    at https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:1062122
    at lo (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:1062152)
    at e.995340.t.render (https://discord.com/assets/web.3d2e76993c4bf346a249.js:12:1065848)
    at MyReact.render (betterdiscord://plugins/0BDFDB.plugin.js:2996:40)
    at MyReact.hookCall (betterdiscord://plugins/0BDFDB.plugin.js:3011:23)
    at loadLibrary (betterdiscord://plugins/0BDFDB.plugin.js:8018:60)
    at parseData (betterdiscord://plugins/0BDFDB.plugin.js:1206:24)
    at parseCSS (betterdiscord://plugins/0BDFDB.plugin.js:1167:122)
    at requestLibraryData (betterdiscord://plugins/0BDFDB.plugin.js:1211:51)
    at eval (betterdiscord://plugins/0BDFDB.plugin.js:1157:7)
    at eval (betterdiscord://plugins/0BDFDB.plugin.js:222:56)
[2024-11-07 15:15:14.203][CONSOLE:LOG] [BDFDB] (v3.8.5) Finished loading Library
...
[2024-11-07 15:15:24.984][CONSOLE:LOG] [PluginRepo] (v2.5.8) Finished fetching Plugins

**Comment by Patcheresu** [comment]
Think this is a Better Discord error, not a BDFDB error, it occurred after I disabled everything with DevilBro on it.
![Discord_2024-11-07_13-48-54](https://github.com/user-attachments/assets/43ee49da-dc11-410b-aed2-aedc2a4cc341)
