### ISSUE TITLE
[BUG] - BDFDB

### ISSUE THREAD

**Issue by romanin-rf** [mwittrien/BetterDiscordAddons#2813]
**Describe the bug**
`Discord crashes when you open your favorite GIFs.`

**To Reproduce**
`...`

**Expected behavior**
`...`

**Screenshots**
`...`

**Discord Build (stable, ptb or canary):**
`stable`

**Additional context**
The first error in **`debug.log`**:
```
================= Starting Debug Log (2024-11-08 12:49:20.540) =================
[2024-11-08 12:49:21.906][CONSOLE:ERROR] Menu API only allows Items and groups of Items as children. Received function g(e){return null} (object) instead
Error: Menu API only allows Items and groups of Items as children. Received function g(e){return null} (object) instead
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:12:2551475
    at Array.reduce (<anonymous>)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:2550263)
    at v (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:2551684)
    at eval (betterdiscord://plugins/0BDFDB.plugin.js:3012:21)
    at ah (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:995893)
    at l (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1053577)
    at oU (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1036572)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1036438
    at ok (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1036446)
    at oR (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1033531)
    at r6 (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:982257)
    at oD (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1034035)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1062122
    at lo (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1062152)
    at e.995340.t.render (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1065848)
    at MyReact.render (betterdiscord://plugins/0BDFDB.plugin.js:2996:40)
    at MyReact.hookCall (betterdiscord://plugins/0BDFDB.plugin.js:3011:23)
    at loadLibrary (betterdiscord://plugins/0BDFDB.plugin.js:8018:60)
    at parseData (betterdiscord://plugins/0BDFDB.plugin.js:1206:24)
    at parseCSS (betterdiscord://plugins/0BDFDB.plugin.js:1167:122)
    at requestLibraryData (betterdiscord://plugins/0BDFDB.plugin.js:1211:51)
    at eval (betterdiscord://plugins/0BDFDB.plugin.js:1157:7)
    at eval (betterdiscord://plugins/0BDFDB.plugin.js:222:56)
```

**Comment by mwittrien** [comment]
What makes you think its related to BDFDB? The error has nothing to do with it

**Comment by romanin-rf** [comment]
If that's the case, it's weird. I disabled all other plugins and completely restarted Discord.

**Comment by romanin-rf** [comment]
Then I close issues...
