### ISSUE TITLE
[BUG] - BDFDB - Menu API only allows Items and groups of Items as children

### ISSUE THREAD

**Issue by Pharaoh2k** [mwittrien/BetterDiscordAddons#2818]
**Describe the bug**
Console error on initalization

**To Reproduce**
Console error on initalization.

**Expected behavior**
No error.

**Screenshots**
-

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Getting this error when BD intializes:
```
Error: Menu API only allows Items and groups of Items as children. Received function g(e){return null} (object) instead
    at web.d9bea0e6d6b17037157b.js:12:2549598
    at Array.reduce (<anonymous>)
    at e (web.d9bea0e6d6b17037157b.js:12:2548386)
    at v (web.d9bea0e6d6b17037157b.js:12:2549807)
    at eval (0BDFDB.plugin.js:3012:21)
    at ap (web.d9bea0e6d6b17037157b.js:12:995051)
    at l (web.d9bea0e6d6b17037157b.js:12:1052735)
    at oU (web.d9bea0e6d6b17037157b.js:12:1035730)
    at web.d9bea0e6d6b17037157b.js:12:1035596
    at ok (web.d9bea0e6d6b17037157b.js:12:1035604)
    at oR (web.d9bea0e6d6b17037157b.js:12:1032689)
    at r6 (web.d9bea0e6d6b17037157b.js:12:981415)
    at oD (web.d9bea0e6d6b17037157b.js:12:1033193)
    at web.d9bea0e6d6b17037157b.js:12:1061280
    at lo (web.d9bea0e6d6b17037157b.js:12:1061310)
    at t.render (web.d9bea0e6d6b17037157b.js:12:1065006)
    at MyReact.render (0BDFDB.plugin.js:2996:40)
    at MyReact.hookCall (0BDFDB.plugin.js:3011:23)
    at loadLibrary (0BDFDB.plugin.js:8020:60)
    at parseData (0BDFDB.plugin.js:1206:24)
    at parseCSS (0BDFDB.plugin.js:1167:122)
    at requestLibraryData (0BDFDB.plugin.js:1211:51)
    at eval (0BDFDB.plugin.js:1157:7)
    at eval (0BDFDB.plugin.js:222:56)
```

Checked for some insights and got this info:
This error is related to the BDFDB library plugin in BetterDiscord, specifically regarding how it's handling menu items. The error indicates that the Menu API is receiving an invalid child element (a function returning null) when it expects only Menu Items or groups of Menu Items.

**Comment by mwittrien** [comment]
Ignore it
