### ISSUE TITLE
[BUG] - BlurNSFW

### ISSUE THREAD

**Issue by alsoGAMER** [mwittrien/BetterDiscordAddons#514]
**Describe the bug**
```
[EnhancedDiscord] [BlurNSFW] Failed to load:
ReferenceError: ModalActions is not defined
    at Function.showConfirmationModal (/home/USER/Documents/EnhancedDiscord/dom_shit.js:291:9)
    at module.exports.global.ZeresPluginLibrary.plugin.Patcher.Patcher.load (/home/USER/Documents/EnhancedDiscord/plugins/BlurNSFW.plugin.js:43:19)
    at Plugin.load (/home/USER/Documents/EnhancedDiscord/bd_shit.js:134:29)
    at loadPlugin (/home/USER/Documents/EnhancedDiscord/dom_shit.js:87:16)
    at process.<anonymous> (/home/USER/Documents/EnhancedDiscord/dom_shit.js:197:9)
(anonymous) @ 202cf4cccacc9609a8bc.js:16
```

**To Reproduce**
Start Discord with EnhancedDiscord injected and BlurNSFW enabled

**Expected behavior**
The plugin would load normally.

**Discord Built (stable, PTB or canary):**
Stable 0.0.12

**Additional context**
I don't know if this is an issue with EnhancedDiscord, so let me know if I should notify them of this issue.

**Comment by mwittrien** [comment]
Not my plugin

**Comment by alsoGAMER** [comment]
> Not my plugin 
> 

So I've to contact the EnhancedDiscord support?

**Comment by mwittrien** [comment]
Conact the author of the plugin, not me
